worker_processes 4;

events { 
    worker_connections 1024; 
    }

http {
    include mime.types;
    upstream users_ms {
        server host.docker.internal:4001;
    }

    upstream product_ms {
        server host.docker.internal:4002;
    }

    upstream order_ms {
        server host.docker.internal:4003;
    }
    server{
        listen 80;
        server_name localhost;
    
        location /api/users/ {
            proxy_pass http://users_ms/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
           
        }
         location /api/products/ {
            proxy_pass http://product_ms/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
         location /api/orders/ {
            proxy_pass http://order_ms/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}